import { Quote } from "./quote.js"
export const allQuotes = [
    new Quote((str) => `Chat you're too ${str}! wait, no`, "entertaining"),
    new Quote((str) => `I should be more ${str} fisted`, "iron"),
    new Quote((str) => `I love ${str}. ${str} is my friend.`, "Inland Empire"),
    new Quote((str) => `That's me! I'm ${str}!`, "piggo"),
    new Quote((str) => `You can't ${str} onto feet forever`, "hold"),
    new Quote((str) => `who's the real ${str}? woof!`, "alpha"),
    new Quote((str) => `It's always a gender... Oh sorry, a ${str}!`, "journey"),
    new Quote((str) => `I swear the Art Of War by Sun Tzu is a ${str} read.`, "quick"),
    new Quote((str) => `I am nerd ${str}`, "behaviour"),
    new Quote((str) => `${str} enough to pick up the children, but not ${str} enough to pick up the panda bear. I see how it is.`, "big"),
    new Quote((str) => `I cant '${str}'. I'll practise off-stream...`, "boing"),
    new Quote((str) => `Monarchs are ${str}! I agree`, "lovely"),
    new Quote((str) => `I wish I could get more ${str} ...but I'm a man`, "empathy"),
    new Quote((str) => `${str}? You mean when there are too many boys in me...my stomach`, "Boisterous"),
    new Quote((str) => `Strong male ${str} needs to be put aside for this art`, "tiddy"),
    new Quote((str) => `Streamer goals. I wish to be ${str}able, y'know?`, "haul"),
    new Quote((str) => `Do not ${str} me! I am not a homeopathic remedy`, "dilute"),
]